package com.upgrad.FoodOrderingApp.service.entitiy;

// Generated 15 Jun, 2019 9:01:22 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Address generated by hbm2java
 */
@Entity
@Table(name = "address", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "uuid"))
public class AddressEntity implements java.io.Serializable {

	private int id;
	private State state;
	private String uuid;
	private String flatBuilNumber;
	private String locality;
	private String city;
	private String pincode;
	private Integer active;
	private Set<Restaurant> restaurants = new HashSet<Restaurant>(0);
	private Set<Orders> orderses = new HashSet<Orders>(0);
	private Set<CustomerAddress> customerAddresses = new HashSet<CustomerAddress>(
			0);

	public AddressEntity() {
	}

	public AddressEntity(int id, String uuid) {
		this.id = id;
		this.uuid = uuid;
	}

	public AddressEntity(int id, State state, String uuid, String flatBuilNumber,
			String locality, String city, String pincode, Integer active,
			Set<Restaurant> restaurants, Set<Orders> orderses,
			Set<CustomerAddress> customerAddresses) {
		this.id = id;
		this.state = state;
		this.uuid = uuid;
		this.flatBuilNumber = flatBuilNumber;
		this.locality = locality;
		this.city = city;
		this.pincode = pincode;
		this.active = active;
		this.restaurants = restaurants;
		this.orderses = orderses;
		this.customerAddresses = customerAddresses;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "state_id")
	public State getState() {
		return this.state;
	}

	public void setState(State state) {
		this.state = state;
	}

	@Column(name = "uuid", unique = true, nullable = false, length = 200)
	public String getUuid() {
		return this.uuid;
	}

	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

	@Column(name = "flat_buil_number")
	public String getFlatBuilNumber() {
		return this.flatBuilNumber;
	}

	public void setFlatBuilNumber(String flatBuilNumber) {
		this.flatBuilNumber = flatBuilNumber;
	}

	@Column(name = "locality")
	public String getLocality() {
		return this.locality;
	}

	public void setLocality(String locality) {
		this.locality = locality;
	}

	@Column(name = "city", length = 30)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "pincode", length = 30)
	public String getPincode() {
		return this.pincode;
	}

	public void setPincode(String pincode) {
		this.pincode = pincode;
	}

	@Column(name = "active")
	public Integer getActive() {
		return this.active;
	}

	public void setActive(Integer active) {
		this.active = active;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "address")
	public Set<Restaurant> getRestaurants() {
		return this.restaurants;
	}

	public void setRestaurants(Set<Restaurant> restaurants) {
		this.restaurants = restaurants;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "address")
	public Set<Orders> getOrderses() {
		return this.orderses;
	}

	public void setOrderses(Set<Orders> orderses) {
		this.orderses = orderses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "address")
	public Set<CustomerAddress> getCustomerAddresses() {
		return this.customerAddresses;
	}

	public void setCustomerAddresses(Set<CustomerAddress> customerAddresses) {
		this.customerAddresses = customerAddresses;
	}

}
