package com.upgrad.FoodOrderingApp.service.entitiy;

// Generated 15 Jun, 2019 9:01:22 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Coupon generated by hbm2java
 */
@Entity
@Table(name = "coupon", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "uuid"))
public class Coupon implements java.io.Serializable {

	private int id;
	private String uuid;
	private String couponName;
	private int percent;
	private Set<Orders> orderses = new HashSet<Orders>(0);

	public Coupon() {
	}

	public Coupon(int id, String uuid, int percent) {
		this.id = id;
		this.uuid = uuid;
		this.percent = percent;
	}

	public Coupon(int id, String uuid, String couponName, int percent,
			Set<Orders> orderses) {
		this.id = id;
		this.uuid = uuid;
		this.couponName = couponName;
		this.percent = percent;
		this.orderses = orderses;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "uuid", unique = true, nullable = false, length = 200)
	public String getUuid() {
		return this.uuid;
	}

	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

	@Column(name = "coupon_name")
	public String getCouponName() {
		return this.couponName;
	}

	public void setCouponName(String couponName) {
		this.couponName = couponName;
	}

	@Column(name = "percent", nullable = false)
	public int getPercent() {
		return this.percent;
	}

	public void setPercent(int percent) {
		this.percent = percent;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "coupon")
	public Set<Orders> getOrderses() {
		return this.orderses;
	}

	public void setOrderses(Set<Orders> orderses) {
		this.orderses = orderses;
	}

}
