package com.upgrad.FoodOrderingApp.service.entitiy;

// Generated 15 Jun, 2019 9:01:22 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CustomerAddress generated by hbm2java
 */
@Entity
@Table(name = "customer_address", schema = "public")
public class CustomerAddress implements java.io.Serializable {

	private int id;
	private AddressEntity addressEntity;
	private Customer customer;

	public CustomerAddress() {
	}

	public CustomerAddress(int id, AddressEntity addressEntity, Customer customer) {
		this.id = id;
		this.addressEntity = addressEntity;
		this.customer = customer;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "address_id", nullable = false)
	public AddressEntity getAddress() {
		return this.addressEntity;
	}

	public void setAddress(AddressEntity addressEntity) {
		this.addressEntity = addressEntity;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "customer_id", nullable = false)
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

}
