package com.upgrad.FoodOrderingApp.service.entitiy;

// Generated 15 Jun, 2019 9:01:22 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * CustomerAuth generated by hbm2java
 */
@Entity
@Table(name = "customer_auth", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "uuid"))
public class CustomerAuth implements java.io.Serializable {

	private int id;
	private Customer customer;
	private String uuid;
	private String accessToken;
	private Date loginAt;
	private Date logoutAt;
	private Date expiresAt;

	public CustomerAuth() {
	}

	public CustomerAuth(int id, Customer customer, String uuid) {
		this.id = id;
		this.customer = customer;
		this.uuid = uuid;
	}

	public CustomerAuth(int id, Customer customer, String uuid,
			String accessToken, Date loginAt, Date logoutAt, Date expiresAt) {
		this.id = id;
		this.customer = customer;
		this.uuid = uuid;
		this.accessToken = accessToken;
		this.loginAt = loginAt;
		this.logoutAt = logoutAt;
		this.expiresAt = expiresAt;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "customer_id", nullable = false)
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	@Column(name = "uuid", unique = true, nullable = false, length = 200)
	public String getUuid() {
		return this.uuid;
	}

	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

	@Column(name = "access_token", length = 500)
	public String getAccessToken() {
		return this.accessToken;
	}

	public void setAccessToken(String accessToken) {
		this.accessToken = accessToken;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "login_at", length = 29)
	public Date getLoginAt() {
		return this.loginAt;
	}

	public void setLoginAt(Date loginAt) {
		this.loginAt = loginAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "logout_at", length = 29)
	public Date getLogoutAt() {
		return this.logoutAt;
	}

	public void setLogoutAt(Date logoutAt) {
		this.logoutAt = logoutAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "expires_at", length = 29)
	public Date getExpiresAt() {
		return this.expiresAt;
	}

	public void setExpiresAt(Date expiresAt) {
		this.expiresAt = expiresAt;
	}

}
