package com.upgrad.FoodOrderingApp.service.entitiy;

// Generated 15 Jun, 2019 9:01:22 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Customer generated by hbm2java
 */
@Entity
@Table(name = "customer", schema = "public", uniqueConstraints = {
		@UniqueConstraint(columnNames = "uuid"),
		@UniqueConstraint(columnNames = "contact_number") })
public class Customer implements java.io.Serializable {

	private int id;
	private String uuid;
	private String firstname;
	private String lastname;
	private String email;
	private String contactNumber;
	private String password;
	private String salt;
	private Set<CustomerAuth> customerAuths = new HashSet<CustomerAuth>(0);
	private Set<CustomerAddress> customerAddresses = new HashSet<CustomerAddress>(
			0);
	private Set<Orders> orderses = new HashSet<Orders>(0);

	public Customer() {
	}

	public Customer(int id, String uuid, String firstname,
			String contactNumber, String password, String salt) {
		this.id = id;
		this.uuid = uuid;
		this.firstname = firstname;
		this.contactNumber = contactNumber;
		this.password = password;
		this.salt = salt;
	}

	public Customer(int id, String uuid, String firstname, String lastname,
			String email, String contactNumber, String password, String salt,
			Set<CustomerAuth> customerAuths,
			Set<CustomerAddress> customerAddresses, Set<Orders> orderses) {
		this.id = id;
		this.uuid = uuid;
		this.firstname = firstname;
		this.lastname = lastname;
		this.email = email;
		this.contactNumber = contactNumber;
		this.password = password;
		this.salt = salt;
		this.customerAuths = customerAuths;
		this.customerAddresses = customerAddresses;
		this.orderses = orderses;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "uuid", unique = true, nullable = false, length = 200)
	public String getUuid() {
		return this.uuid;
	}

	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

	@Column(name = "firstname", nullable = false, length = 30)
	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	@Column(name = "lastname", length = 30)
	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	@Column(name = "email", length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "contact_number", unique = true, nullable = false, length = 30)
	public String getContactNumber() {
		return this.contactNumber;
	}

	public void setContactNumber(String contactNumber) {
		this.contactNumber = contactNumber;
	}

	@Column(name = "password", nullable = false)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "salt", nullable = false)
	public String getSalt() {
		return this.salt;
	}

	public void setSalt(String salt) {
		this.salt = salt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customer")
	public Set<CustomerAuth> getCustomerAuths() {
		return this.customerAuths;
	}

	public void setCustomerAuths(Set<CustomerAuth> customerAuths) {
		this.customerAuths = customerAuths;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customer")
	public Set<CustomerAddress> getCustomerAddresses() {
		return this.customerAddresses;
	}

	public void setCustomerAddresses(Set<CustomerAddress> customerAddresses) {
		this.customerAddresses = customerAddresses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customer")
	public Set<Orders> getOrderses() {
		return this.orderses;
	}

	public void setOrderses(Set<Orders> orderses) {
		this.orderses = orderses;
	}

}
