package com.upgrad.FoodOrderingApp.service.entitiy;

// Generated 15 Jun, 2019 9:01:22 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Item generated by hbm2java
 */
@Entity
@Table(name = "item", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "uuid"))
public class Item implements java.io.Serializable {

	private int id;
	private String uuid;
	private String itemName;
	private int price;
	private String type;
	private Set<OrderItem> orderItems = new HashSet<OrderItem>(0);
	private Set<CategoryItem> categoryItems = new HashSet<CategoryItem>(0);
	private Set<RestaurantItem> restaurantItems = new HashSet<RestaurantItem>(0);

	public Item() {
	}

	public Item(int id, String uuid, String itemName, int price, String type) {
		this.id = id;
		this.uuid = uuid;
		this.itemName = itemName;
		this.price = price;
		this.type = type;
	}

	public Item(int id, String uuid, String itemName, int price, String type,
			Set<OrderItem> orderItems, Set<CategoryItem> categoryItems,
			Set<RestaurantItem> restaurantItems) {
		this.id = id;
		this.uuid = uuid;
		this.itemName = itemName;
		this.price = price;
		this.type = type;
		this.orderItems = orderItems;
		this.categoryItems = categoryItems;
		this.restaurantItems = restaurantItems;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "uuid", unique = true, nullable = false, length = 200)
	public String getUuid() {
		return this.uuid;
	}

	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

	@Column(name = "item_name", nullable = false, length = 30)
	public String getItemName() {
		return this.itemName;
	}

	public void setItemName(String itemName) {
		this.itemName = itemName;
	}

	@Column(name = "price", nullable = false)
	public int getPrice() {
		return this.price;
	}

	public void setPrice(int price) {
		this.price = price;
	}

	@Column(name = "type", nullable = false, length = 10)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "item")
	public Set<OrderItem> getOrderItems() {
		return this.orderItems;
	}

	public void setOrderItems(Set<OrderItem> orderItems) {
		this.orderItems = orderItems;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "item")
	public Set<CategoryItem> getCategoryItems() {
		return this.categoryItems;
	}

	public void setCategoryItems(Set<CategoryItem> categoryItems) {
		this.categoryItems = categoryItems;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "item")
	public Set<RestaurantItem> getRestaurantItems() {
		return this.restaurantItems;
	}

	public void setRestaurantItems(Set<RestaurantItem> restaurantItems) {
		this.restaurantItems = restaurantItems;
	}

}
