package com.upgrad.FoodOrderingApp.service.entitiy;

// Generated 15 Jun, 2019 9:01:22 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Orders generated by hbm2java
 */
@Entity
@Table(name = "orders", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "uuid"))
public class Orders implements java.io.Serializable {

	private int id;
	private AddressEntity addressEntity;
	private Customer customer;
	private Coupon coupon;
	private Restaurant restaurant;
	private Payment payment;
	private String uuid;
	private BigDecimal bill;
	private BigDecimal discount;
	private Date date;
	private Set<OrderItem> orderItems = new HashSet<OrderItem>(0);

	public Orders() {
	}

	public Orders(int id, AddressEntity addressEntity, Customer customer,
			Restaurant restaurant, String uuid, BigDecimal bill, Date date) {
		this.id = id;
		this.addressEntity = addressEntity;
		this.customer = customer;
		this.restaurant = restaurant;
		this.uuid = uuid;
		this.bill = bill;
		this.date = date;
	}

	public Orders(int id, AddressEntity addressEntity, Customer customer, Coupon coupon,
			Restaurant restaurant, Payment payment, String uuid,
			BigDecimal bill, BigDecimal discount, Date date,
			Set<OrderItem> orderItems) {
		this.id = id;
		this.addressEntity = addressEntity;
		this.customer = customer;
		this.coupon = coupon;
		this.restaurant = restaurant;
		this.payment = payment;
		this.uuid = uuid;
		this.bill = bill;
		this.discount = discount;
		this.date = date;
		this.orderItems = orderItems;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "address_id", nullable = false)
	public AddressEntity getAddress() {
		return this.addressEntity;
	}

	public void setAddress(AddressEntity addressEntity) {
		this.addressEntity = addressEntity;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "customer_id", nullable = false)
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "coupon_id")
	public Coupon getCoupon() {
		return this.coupon;
	}

	public void setCoupon(Coupon coupon) {
		this.coupon = coupon;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "restaurant_id", nullable = false)
	public Restaurant getRestaurant() {
		return this.restaurant;
	}

	public void setRestaurant(Restaurant restaurant) {
		this.restaurant = restaurant;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "payment_id")
	public Payment getPayment() {
		return this.payment;
	}

	public void setPayment(Payment payment) {
		this.payment = payment;
	}

	@Column(name = "uuid", unique = true, nullable = false, length = 200)
	public String getUuid() {
		return this.uuid;
	}

	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

	@Column(name = "bill", nullable = false, precision = 131089, scale = 0)
	public BigDecimal getBill() {
		return this.bill;
	}

	public void setBill(BigDecimal bill) {
		this.bill = bill;
	}

	@Column(name = "discount", precision = 131089, scale = 0)
	public BigDecimal getDiscount() {
		return this.discount;
	}

	public void setDiscount(BigDecimal discount) {
		this.discount = discount;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date", nullable = false, length = 29)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "orders")
	public Set<OrderItem> getOrderItems() {
		return this.orderItems;
	}

	public void setOrderItems(Set<OrderItem> orderItems) {
		this.orderItems = orderItems;
	}

}
