package com.upgrad.FoodOrderingApp.service.entitiy;

// Generated 15 Jun, 2019 9:01:22 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RestaurantCategory generated by hbm2java
 */
@Entity
@Table(name = "restaurant_category", schema = "public")
public class RestaurantCategory implements java.io.Serializable {

	private int id;
	private Category category;
	private Restaurant restaurant;

	public RestaurantCategory() {
	}

	public RestaurantCategory(int id, Category category, Restaurant restaurant) {
		this.id = id;
		this.category = category;
		this.restaurant = restaurant;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "category_id", nullable = false)
	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "restaurant_id", nullable = false)
	public Restaurant getRestaurant() {
		return this.restaurant;
	}

	public void setRestaurant(Restaurant restaurant) {
		this.restaurant = restaurant;
	}

}
