package com.upgrad.FoodOrderingApp.service.entitiy;
// Generated 15 Jun, 2019 9:01:22 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * State generated by hbm2java
 */
@Entity
@Table(name = "state")
public class State implements java.io.Serializable {

	private int id;
	private String uuid;
	private String stateName;
	private Set<AddressEntity> addresses = new HashSet<AddressEntity>(0);

	public State() {
	}

	public State(int id, String uuid) {
		this.id = id;
		this.uuid = uuid;
	}

	public State(int id, String uuid, String stateName, Set<AddressEntity> addresses) {
		this.id = id;
		this.uuid = uuid;
		this.stateName = stateName;
		this.addresses = addresses;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "uuid", unique = true, nullable = false, length = 200)
	public String getUuid() {
		return this.uuid;
	}

	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

	@Column(name = "state_name", length = 30)
	public String getStateName() {
		return this.stateName;
	}

	public void setStateName(String stateName) {
		this.stateName = stateName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "state")
	public Set<AddressEntity> getAddresses() {
		return this.addresses;
	}

	public void setAddresses(Set<AddressEntity> addresses) {
		this.addresses = addresses;
	}

}
