package com.upgrad.FoodOrderingApp.service.entity;

// Generated 15 Jun, 2019 9:01:22 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * CategoryEntity generated by hbm2java
 */
@Entity
@Table(name = "category", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "uuid"))
public class CategoryEntity implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private String uuid;
	private String categoryName;
	private Set<RestaurantCategoryEntity> restaurantCategories = new HashSet<RestaurantCategoryEntity>(
			0);
	private Set<CategoryItemEntity> categoryItems = new HashSet<CategoryItemEntity>(0);

	public CategoryEntity() {
	}

	public CategoryEntity(int id, String uuid) {
		this.id = id;
		this.uuid = uuid;
	}

	public CategoryEntity(int id, String uuid, String categoryName,
                           Set<RestaurantCategoryEntity> restaurantCategories,
                           Set<CategoryItemEntity> categoryItems) {
		this.id = id;
		this.uuid = uuid;
		this.categoryName = categoryName;
		this.restaurantCategories = restaurantCategories;
		this.categoryItems = categoryItems;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "uuid", unique = true, nullable = false, length = 200)
	public String getUuid() {
		return this.uuid;
	}

	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

	@Column(name = "category_name")
	public String getCategoryName() {
		return this.categoryName;
	}

	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "id")
	public Set<RestaurantCategoryEntity> getRestaurantCategories() {
		return restaurantCategories;
	}
	
	public void setRestaurantCategories(Set<RestaurantCategoryEntity> restaurantCategories) {
		this.restaurantCategories = restaurantCategories;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "id")
	public Set<CategoryItemEntity> getCategoryItems() {
		return categoryItems;
	}

	public void setCategoryItems(Set<CategoryItemEntity> categoryItems) {
		this.categoryItems = categoryItems;
	}	
}
