package com.upgrad.FoodOrderingApp.service.entity;

// Generated 15 Jun, 2019 9:01:22 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * CategoryItem generated by hbm2java
 */
@Entity
@Table(name = "category_item", schema = "public",uniqueConstraints = @UniqueConstraint(columnNames = "id"))
public class CategoryItemEntity implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private Item item;
	private CategoryEntity categoryEntity;

	public CategoryItemEntity() {
	}

	public CategoryItemEntity(int id, Item item, CategoryEntity categoryEntity) {
		this.id = id;
		this.item = item;
		this.categoryEntity = categoryEntity;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "item_id", nullable = false)
	public Item getItem() {
		return this.item;
	}

	public void setItem(Item item) {
		this.item = item;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "category_id", nullable = false)
	public CategoryEntity getCategoryEntity() {
		return this.categoryEntity;
	}

	public void setCategoryEntity(CategoryEntity categoryEntity) {
		this.categoryEntity = categoryEntity;
	}

}
