package com.upgrad.FoodOrderingApp.service.entity;

// Generated 15 Jun, 2019 9:01:22 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RestaurantCategory generated by hbm2java
 */
@Entity
@Table(name = "restaurant_category", schema = "public")
public class RestaurantCategoryEntity implements java.io.Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private CategoryEntity categoryEntity;
	private Restaurant restaurant;

	public RestaurantCategoryEntity() {
	}

	public RestaurantCategoryEntity(int id, CategoryEntity categoryEntity, Restaurant restaurant) {
		this.id = id;
		this.categoryEntity = categoryEntity;
		this.restaurant = restaurant;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "category_id", nullable = false)
	public CategoryEntity getCategoryEntity() {
		return categoryEntity;
	}
	
	public void setRestaurant(Restaurant restaurant) {
		this.restaurant = restaurant;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "restaurant_id", nullable = false)
	public Restaurant getRestaurant() {
		return this.restaurant;
	}

	public void setCategoryEntity(CategoryEntity categoryEntity) {
		this.categoryEntity = categoryEntity;
	}
}
